spring.application.name=guesstheword
spring.datasource.url=jdbc:sqlite:guessword.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
app.admin.username=Administrator
app.admin.password=Admin$123